GET http://localhost:5198

####
GET http://localhost:5198/users/1/posts/buffalo

####
GET http://localhost:5198/blogs


####
GET http://localhost:5198/blogs/4



####
POST http://localhost:5198/blogs
Content-Type: application/json

{
    "title": "My fourth blog",
    "body": "This is my fourth blog"
}

###
PUT http://localhost:5198/blogs/0
Content-Type: application/json

{
    "title": "Hello first blog",
    "body": "I changed the content of the first blog"
}

###
DELETE http://localhost:5198/blogs/0


###
GET http://localhost:5198/products/10


###
GET http://localhost:5198/products/mobile-phone/324245


###
GET http://localhost:5198/files/images/cats/cat_1.jpg



###
GET http://localhost:5198/search?q=dotnet&page=2

###
GET http://localhost:5198/store/electronics/123/onSale


###
GET http://localhost:5198/store/electronics/sale?inStock=true




####
GET http://localhost:5198/downloads


####
DELETE http://localhost:5198



####
POST http://localhost:5198



####
PUT http://localhost:5198

